# 模型参数
model:
  in_channels: 4        # 输入通道数(RGBA)
  base_channels: 32     # 基础通道数

# 训练参数
train:
  batch_size: 32     # 批量大小
  epochs: 100        # 训练轮数
  lr_g: 0.0002          # Generator学习率
  lr_d: 0.0002          # Discriminator学习率
  lambda_adv: 0.01      # 对抗损失权重
  lambda_fm: 0.1        # 特征匹配损失权重
  lambda_alpha: 0.1     # Alpha二值化损失权重
  h: 48                 # 图像高度
  w: 32                 # 图像宽度
  dataset_path: "TrainningData/Octopath"  # 训练集路径
  val_ratio: 0.1
  test_ratio: 0.0
  seed: 42
  num_workers: 0
  sample_every: 10

# 其他参数
misc:
  checkpoints_path: "./checkpoints"  # 模型保存路径
  tb_port: 6006                      # TensorBoard 端口号，默认 6006。训练时会自动检测并在此端口开启 TensorBoard 服务
